name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - hugo
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.161.1'
          extended: true

      - name: Initialize Hugo Module
        run: |
          hugo mod init github.com/Seek-Key-LTD/kunpengzhi
          hugo mod get github.com/theNewDynamic/gohugo-theme-ananke@latest

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages